/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.orimwulong.gamefinder;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GameFinderTest {
    @Test void dummyTest() {
        assertFalse(1 == 2, "GameFinder must init fully");
    }
}
