/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.orimwulong.gamefinder;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GameFinderTest {
    @Test void initFully() {
        GameFinder gf = new GameFinder();
        assertTrue(gf.init(), "GameFinder must init fully");
    }
}
