/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.orimwulong.gamefinder;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GameFinderTest {
    @Test void initFully() {
        GameFinder classUnderTest = new GameFinder();
        assertTrue(classUnderTest.init());
    }
}
